name = "Vectorize"
uuid = "922354f6-6876-5285-8954-7bb8005415d2"
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Julia = ">= 0.7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[targets]
build = ["Libdl"]
test = ["Test", "Random", "SpecialFunctions"]
